#!/bin/bash

configuration="$1"
echo $configuration
pattern="$CELLWORLD_CACHE/cell_group"

echo $pattern

for f in "${pattern}"/${configuration}*.occlusions
do
  #
  parts=$(echo $f | tr "." "\n")
  IFS='.' read -ra parts <<< "$f"
  occlusions=$(echo "${parts[1]}")
  echo $occlusions
  ../cmake-build-debug/create_paths -c ${configuration} -o $occlusions > "$CELLWORLD_CACHE/paths/${configuration}.${occlusions}.astar" &
  ../cmake-build-debug/create_visibility -c ${configuration} -o $occlusions > "$CELLWORLD_CACHE/graph/${configuration}.${occlusions}.cell_visibility" &
done

