#!/bin/bash

for WORLD_NUMBER in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19; do
  for ENTROPY_BUCKET in 00 01 02 03 04 05 06 07 08 09 10; do
    WORLD="${WORLD_NUMBER}_${ENTROPY_BUCKET}"
    ../cmake-build-debug/create_options -o $WORLD > "$CELLWORLD_CACHE/graph/hexagonal.$WORLD.options"
  done
done

