#!/bin/bash
CELLWORLD_CACHE=/mnt/c/Research/cellworld_data
CELLWORLD_PLANNER_BIN=/mnt/c/Research/cellworld_planner/cmake-build-release
WORLD_STATS_FOLDER="$CELLWORLD_CACHE/world_statistics"

WORLD_TYPE=hexagonal

mkdir -p $WORLD_STATS_FOLDER

for WORLD_NUMBER in 00 01 02 03 04 05 06 07 08 09 10 11 12 13 14 15 16 17 18 19; do
  for ENTROPY_BUCKET in 00 01 02 03 04 05 06 07 08 09; do
    WORLD="${WORLD_NUMBER}_${ENTROPY_BUCKET}"
    echo "$CELLWORLD_PLANNER_BIN/create_world_statistics -c $WORLD_TYPE -i canonical -o $WORLD -s $CELLWORLD_CACHE/world_statistics/$WORLD_TYPE.$WORLD"
    $CELLWORLD_PLANNER_BIN/create_world_statistics -c $WORLD_TYPE -i canonical -o $WORLD -s $CELLWORLD_CACHE/world_statistics/$WORLD_TYPE.$WORLD
#    $CELLWORLD_PLANNER_BIN/show_stats -o $WORLD -c $WORLD_TYPE
  done
done