#!/bin/bash
worker_count=$(getconf _NPROCESSORS_ONLN)
sim_count=0

for DEPTH in "5" "10" "15" "20" "25" "50" "100" "200" "300" "400" "500" "600" "700" "800" "900" "1000" "2000" "3000"
do
  POMCP_simulation_folder="${CELLWORLD_PLANNER}/simulation_results/POMCP_ICRA_08_${DEPTH}"
  if [ ! -d "$POMCP_simulation_folder" ]
  then
    configuration="${stringarray[0]}"
    world="${stringarray[1]}"
    #runs the simulation
    sim_count=$((sim_count + 1))
    active_workers=$(jobs -p | wc -l)
    while (( active_workers>=worker_count))
    do
        sleep .1
        active_workers=$(jobs -p | wc -l)
    done
      params=$(echo "-wc hexagonal -o 21_05 -wc ${configuration} -e 2 -o $world -out $POMCP_simulation_folder -t $DEPTH -sc 150 -rl -p slow_10_randomness -st -r reward2")
      #echo "launching $params"
      (
        $CELLWORLD_PLANNER_BIN/random_world_sim $params
      ) &
    fi
  LPPO_simulation_folder="${CELLWORLD_PLANNER}/simulation_results/POMCP_ICRA_08_${DEPTH}"
  if [ ! -d "$LPPO_simulation_folder" ]
  then
    configuration="${stringarray[0]}"
    world="${stringarray[1]}"
    #runs the simulation
    sim_count=$((sim_count + 1))
    active_workers=$(jobs -p | wc -l)
    while (( active_workers>=worker_count))
    do
        sleep .1
        active_workers=$(jobs -p | wc -l)
    done
      params=$(echo "-wc hexagonal -o 21_05 -wc ${configuration} -e 2 -o $world -out $LPPO_simulation_folder -t $DEPTH -sc 150 -rp -p slow_10_randomness -st -r reward2")
#      echo "launching $params"
      (
        $CELLWORLD_PLANNER_BIN/random_world_sim $params
      ) &
    fi
done
while ((active_workers>0))
do
    sleep 1
    active_workers=$(jobs -p | wc -l)
    jobs > /dev/null
done