#!/bin/bash

configuration="$1"
world_number="$2"

active_processes=0;

count_processes () {
  new_active_processes=0
  for pid in ${pids[*]}; do
      if ps -p $pid > /dev/null
      then
        new_active_processes=$((new_active_processes+1))
      fi
  done
  active_processes=$((new_active_processes))
}

folder="${CELLWORLD_PLANNER}/simulation_results/random_world"

for e in {0..9}
do
  world="${world_number}_0${e}"
  if ls $folder/${configuration}.${world}.* 1> /dev/null 2>&1
  then
    #simulation results found
    echo "${world} found"
  else
    #runs the simulation
    count_processes
    while [[ active_processes -gt  1 ]];
    do
      count_processes
      sleep 1
    done
    $CELLWORLD_PLANNER_BIN/random_world_sim -wc ${configuration} -o $world ${@:3} &
    pids[${e}]=$!
  fi
done
