#!/bin/bash

ss=$4
if [ "$ss" == '' ]; then
  ss="0"
fi

se=$5
if [ "$se" == '' ]; then
  se="100"
fi

export CELLWORLD_CACHE=/mnt/c/Research/cellworld_data

../cmake-build-debug/simulation -c $1 -o $2 -r $3 -ss $ss -se $se

