#!/bin/bash

results_folder="${CELLWORLD_PLANNER}/simulation_results/$1"

worker_count=$(getconf _NPROCESSORS_ONLN)
jobs=()
sim_count=0
simulation_date=$(date +"%Y%m%d_%H%M")
while IFS= read -r line; do
  stringarray=($line)
  configuration="${stringarray[0]}"
  world="${stringarray[1]}"
  if ls $folder/${configuration}.${world}.* 1> /dev/null 2>&1
  then
    #simulation results found
    echo "${world} found"
  else
    #runs the simulation
    sim_count=$((sim_count + 1))
    active_workers=$(jobs -p | wc -l)
    while (( active_workers>=worker_count))
    do
        sleep .1
        active_workers=$(jobs -p | wc -l)
    done
      echo "launching $CELLWORLD_PLANNER_BIN/random_world_sim -wc ${configuration} -o $world -out $folder ${@:2}"
      (
      simulation_folder="${results_folder}/${configuration}_${world}_${simulation_date}"
      $CELLWORLD_PLANNER_BIN/random_world_sim -wc ${configuration} -o $world -out $simulation_folder ${@:2}
      ) &
  fi
done

while ((active_workers>0))
do
    sleep 1
    active_workers=$(jobs -p | wc -l)
    jobs
done

echo $jobs
